version: 2

updates:

  - package-ecosystem: "composer"
    commit-message:
      include: "scope"
      prefix: "composer"
    directory: "/src/php"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    commit-message:
      include: "scope"
      prefix: "github-actions"
    # default location of `.github/workflows`
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"